"""Stable, redacted error types for the DWG pipeline."""

from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    """Machine-readable, fail-closed failure categories."""

    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    ODA_NOT_FOUND = "ODA_NOT_FOUND"
    ODA_DISCOVERY_AMBIGUOUS = "ODA_DISCOVERY_AMBIGUOUS"
    ODA_VERSION_UNSUPPORTED = "ODA_VERSION_UNSUPPORTED"
    ODA_TIMEOUT = "ODA_TIMEOUT"
    ODA_OUTPUT_INCOMPATIBLE = "ODA_OUTPUT_INCOMPATIBLE"
    CONVERSION_FAILURE = "CONVERSION_FAILURE"
    UNSUPPORTED_VERSION = "UNSUPPORTED_VERSION"
    STALE_AUDIT = "STALE_AUDIT"
    AUDIT_SCHEMA_INVALID = "AUDIT_SCHEMA_INVALID"
    PLAN_SCHEMA_INVALID = "PLAN_SCHEMA_INVALID"
    VERIFICATION_SCHEMA_INVALID = "VERIFICATION_SCHEMA_INVALID"
    PLAN_AUDIT_MISMATCH = "PLAN_AUDIT_MISMATCH"
    TOOL_VERSION_MISMATCH = "TOOL_VERSION_MISMATCH"
    MISSING_HANDLE = "MISSING_HANDLE"
    CHANGED_ENTITY = "CHANGED_ENTITY"
    DUPLICATE_TARGET = "DUPLICATE_TARGET"
    UNSAFE_ENTITY_TYPE = "UNSAFE_ENTITY_TYPE"
    NO_ACTIONABLE_FINDINGS = "NO_ACTIONABLE_FINDINGS"
    RE_AUDIT_MISMATCH = "RE_AUDIT_MISMATCH"
    OUTPUT_EXISTS = "OUTPUT_EXISTS"
    OUTPUT_PARENT_MISSING = "OUTPUT_PARENT_MISSING"
    WINDOWS_PLATFORM_REQUIRED = "WINDOWS_PLATFORM_REQUIRED"
    ATOMIC_PUBLISH_FAILED = "ATOMIC_PUBLISH_FAILED"
    PUBLICATION_CLEANUP_FAILURE = "PUBLICATION_CLEANUP_FAILURE"
    PUBLICATION_ROLLBACK_FAILURE = "PUBLICATION_ROLLBACK_FAILURE"
    SOURCE_CHANGED_DURING_RUN = "SOURCE_CHANGED_DURING_RUN"
    OUTPUT_CHANGED_DURING_VERIFY = "OUTPUT_CHANGED_DURING_VERIFY"
    VERIFICATION_ARTIFACT_OWNERSHIP_LOST = "VERIFICATION_ARTIFACT_OWNERSHIP_LOST"
    VERIFICATION_ARTIFACT_CLEANUP_FAILURE = "VERIFICATION_ARTIFACT_CLEANUP_FAILURE"
    SOURCE_LEASE_UNAVAILABLE = "SOURCE_LEASE_UNAVAILABLE"
    LOCAL_REGRESSION_SOURCE_MISSING = "LOCAL_REGRESSION_SOURCE_MISSING"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class PipelineError(Exception):
    """A safe exception whose public representation is only its error code."""

    def __init__(self, code: ErrorCode, internal_reason: str = "") -> None:
        self.code = code
        self.internal_reason = internal_reason
        super().__init__(code.value)

    def redacted_event(self) -> dict[str, str]:
        """Return a log-safe event without internal paths or drawing metadata."""

        return {"status": "error", "code": self.code.value}
